from pyspark.sql import SparkSession
from datetime import datetime, date
import calendar
from dateutil.relativedelta import relativedelta
from pyspark.sql import functions as F

# Iniciar sessão Spark
spark = SparkSession.builder.getOrCreate()

# Definindo função de log, data de processamento e data atual
def log():
    return datetime.now().strftime('%H:%M:%S %d/%m/%Y') + ' >>> ' 

dt_proc = datetime.now().strftime('%Y%m%d%H%M%S')
current_date = datetime.now().strftime('%Y%m%d')

# Definindo data de processamento do book, data inicial de processamento do book como 12 meses atrás
# e data de processamento em formato string para cálculo das janelas de tempo do book
year, month = datetime.now().year, datetime.now().month
last_day = calendar.monthrange(year, month)[1]
last_day_of_month = date(year, month, last_day)

dt_proc_book = last_day_of_month
dt_ini_proc_book = dt_proc_book - relativedelta(months=12)

dt_proc_book = dt_proc_book.strftime('%Y%m')
dt_ini_proc_book = dt_ini_proc_book.strftime('%Y%m')

dt_proc_book_str = last_day_of_month.strftime('%Y-%m-%d')

dt_proc_book, dt_ini_proc_book, dt_proc_book_str


# Opção para data de processamento do book fixa

# dt_proc_book = datetime.now().strptime('2024-09-30', '%Y-%m-%d')
# dt_ini_proc_book = dt_proc_book - relativedelta(months=12)

# dt_proc_book = dt_proc_book.strftime('%Y%m')
# dt_ini_proc_book = dt_ini_proc_book.strftime('%Y%m')

# dt_proc_book_str = datetime.now().strptime('2024-09-30', '%Y-%m-%d').strftime('%Y-%m-%d')

# dt_proc_book, dt_ini_proc_book, dt_proc_book_str

#-------------------------------------- Deduplicação dados Fluxo -----------------------------------------------#

# Lendo tabela de fluxo da camada trusted
tb_fluxo = spark.read.parquet('s3://905418122144-pod-academy-data-lake/03_trusted/tb_fluxo/')
tb_fluxo_00 = tb_fluxo.where(f'ref >= {dt_ini_proc_book} and ref <= {dt_proc_book}')
tb_fluxo_00.createOrReplaceTempView('tb_fluxo_00')


# Conferindo se existem dados duplicados
# spark.sql("""
#     select
#         id_fluxo
#         , count(*)
#     from tb_fluxo_00
#     group by 1
#     order by 2 desc
# """).show(5)


# Criando tabela com chave de deduplicação
tb_fluxo_dedup = spark.sql("""
    select 
        ref || dt_proc as dedup_key
        , *
    from tb_fluxo_00
""")
tb_fluxo_dedup.createOrReplaceTempView('tb_fluxo_dedup')


# Pegando linhas com data de processamento mais recente
tb_fluxo_dedup_00 = spark.sql("""
    select 
        id_fluxo
        , max(dedup_key) as max_dedup_key
    from tb_fluxo_dedup
    group by 1
""")
tb_fluxo_dedup_00.createOrReplaceTempView('tb_fluxo_dedup_00')


# Filtrando tabela apenas pelas linhas com processamento mais recente
tb_fluxo_dedup_01 = spark.sql("""
    select
        a.*
    from tb_fluxo_dedup a
    join tb_fluxo_dedup_00 b 
    on a.id_fluxo = b.id_fluxo
    where a.dedup_key = b.max_dedup_key
""")
tb_fluxo_dedup_01.createOrReplaceTempView('tb_fluxo_dedup_01')


# Conferindo se dados foram deduplicados
# spark.sql("""
#     select
#         id_fluxo
#         , count(*)
#     from tb_fluxo_dedup_01
#     group by 1
#     order by 2 desc
# """).show(5)

#-------------------------------------- Deduplicação dados Acidentes -------------------------------------------#

# Lendo tabela de acidentes da camada trusted
tb_acidentes = spark.read.parquet('s3://905418122144-pod-academy-data-lake/03_trusted/tb_acidentes/')
tb_acidentes_00 = tb_acidentes.where(f'ref >= {dt_ini_proc_book} and ref <= {dt_proc_book}')
tb_acidentes_00.createOrReplaceTempView('tb_acidentes_00')


# Conferindo se existem dados duplicados
# spark.sql("""
#     select
#         id_acidente
#         , count(*)
#     from tb_acidentes_00
#     group by 1
#     order by 2 desc
# """).show(5)


# Criando tabela com chave de deduplicação
tb_acidentes_dedup = spark.sql("""
    select 
        ref || dt_proc as dedup_key
        , *
    from tb_acidentes_00
""")
tb_acidentes_dedup.createOrReplaceTempView('tb_acidentes_dedup')


# Pegando linhas com data de processamento mais recente
tb_acidentes_dedup_00 = spark.sql("""
    select 
        id_acidente
        , max(dedup_key) as max_dedup_key
    from tb_acidentes_dedup
    group by 1
""")
tb_acidentes_dedup_00.createOrReplaceTempView('tb_acidentes_dedup_00')


# Filtrando tabela apenas pelas linhas com processamento mais recente
tb_acidentes_dedup_01 = spark.sql("""
    select
        a.*
    from tb_acidentes_dedup a
    join tb_acidentes_dedup_00 b 
    on a.id_acidente = b.id_acidente
    where a.dedup_key = b.max_dedup_key
""")
tb_acidentes_dedup_01.createOrReplaceTempView('tb_acidentes_dedup_01')


# Conferindo se dados foram deduplicados
# spark.sql("""
#     select
#         id_acidente
#         , count(*)
#     from tb_acidentes_dedup_01
#     group by 1
#     order by 2 desc
# """).show(5)

#------------------------------------------------- Stage -------------------------------------------------------#

# Preparando tabela acidentes para join com tabela fluxo
tb_acidentes_dedup_02 = spark.sql("""
  select
    *
    , case
        when km_acidente >= 525.25 and km_acidente  < 526.55 then 525.900
        when km_acidente  >= 526.55 and km_acidente  < 528.15 then 527.200
        when km_acidente  >= 528.15 and km_acidente  < 529.7 then 529.100
        when km_acidente  >= 529.7 and km_acidente  < 530.76 then 530.300
        when km_acidente  >= 530.76 and km_acidente  < 531.51  then 531.220
        when km_acidente  >= 531.51 and km_acidente  < 532.9 then 531.800
        when km_acidente  >= 532.9 and km_acidente  < 534.125 then 534.000
        when km_acidente  >= 534.125 and km_acidente  < 534.71 then 534.250
        when km_acidente  >= 534.71 and km_acidente  < 535.535 then 535.170
        when km_acidente  >= 535.535 and km_acidente  < 536.7 then 535.900
        when km_acidente  >= 536.7 and km_acidente  < 537.85 then 537.500
        when km_acidente  >= 537.85 and km_acidente  < 538.6 then 538.200
        when km_acidente  >= 538.6 and km_acidente  < 539.75 then 539.000
        when km_acidente  >= 539.75 and km_acidente  < 541.85 then 540.500
        when km_acidente  >= 541.85 and km_acidente  <= 544.55 then 543.200
        else null
    end as km_acidente_categorizado
  from tb_acidentes_dedup_01
  where uf_acidente = 'MG'
""")
tb_acidentes_dedup_02.createOrReplaceTempView('tb_acidentes_dedup_02')


# Join tabela fluxo com tabela acidentes utilizando como chaves km, br, data e sentido
# e selecionando apenas colunas que serão armazenadas na camada stage
df_join = spark.sql("""
  select
    id_fluxo
    , data_fluxo
    , velocidade_fluxo
    , tipo_de_veiculo_fluxo
    , volume_total_fluxo
    , id_acidente
    , data_acidente
    , causa_acidente
    , tipo_acidente
    , classificacao_acidente
    , condicao_metereologica_acidente
    , veiculos_acidente
  from tb_fluxo_dedup_01 as f
  left join tb_acidentes_dedup_02 as a
  on f.km_fluxo = a.km_acidente_categorizado
    and f.br_fluxo = a.br_acidente
    and f.data_fluxo = a.data_acidente
    and f.sentido_fluxo = a.sentido_acidente
""")
df_join.createOrReplaceTempView('df_join')


# Criando variável categórica FLUXO_BAIXO, FLUXO_MEDIO, FLUXO_ALTO
tb_cassificacao_volume = spark.sql("""
  select
    *
    , case
      when volume_total_fluxo >= 1 and volume_total_fluxo < 109 then 'FLUXO_BAIXO'
      when volume_total_fluxo >= 109 and volume_total_fluxo < 217 then 'FLUXO_MEDIO'
      when volume_total_fluxo >= 217 then 'FLUXO_ALTO'
      else null
    end fbc_classificacao_volume
  from df_join
""")
tb_cassificacao_volume.createOrReplaceTempView('tb_cassificacao_volume')


# Criando variável categórica VELOCIDADE_BAIXA, VELOCIDADE_MEDIA, VELOCIDADE_ALTA
tb_cassificacao_velocidade = spark.sql("""
  select
    *
    , case
        when velocidade_fluxo = '<= 20 KM/h' then 'VELOCIDADE_BAIXA'
        when velocidade_fluxo = '21 - 50 KM' then 'VELOCIDADE_BAIXA'
        when velocidade_fluxo = '51 - 80 KM' then 'VELOCIDADE_BAIXA'
        when velocidade_fluxo = '81 - 100 K' then 'VELOCIDADE_MEDIA'
        when velocidade_fluxo = '101 - 120 ' then 'VELOCIDADE_MEDIA'
        when velocidade_fluxo = '121 - 140 ' then 'VELOCIDADE_ALTA'
        when velocidade_fluxo = '141 - 160 ' then 'VELOCIDADE_ALTA'
        when velocidade_fluxo = '> 160 KM/h' then 'VELOCIDADE_ALTA'
      else null
    end fbc_classificacao_velocidade
  from tb_cassificacao_volume
""")
tb_cassificacao_velocidade.createOrReplaceTempView('tb_cassificacao_velocidade')


# Criando variável categórica VEICULO_COMERCIAL, VEICULO_PASSEIO, VEICULO_MOTO, VEICULO_ONIBUS
tb_cassificacao_tipo_veiculo = spark.sql("""
  select
    *
    , case
        when tipo_de_veiculo_fluxo = 'Comercial' then 'VEICULO_COMERCIAL'
        when tipo_de_veiculo_fluxo = 'Passeio' then 'VEICULO_PASSEIO'
        when tipo_de_veiculo_fluxo = 'Moto' then 'VEICULO_MOTO'
        when tipo_de_veiculo_fluxo = 'Ônibus' then 'VEICULO_ONIBUS'
      else null
    end fbc_classificacao_tipo_veiculo
    , row_number() over(partition by data_fluxo order by data_fluxo, id_acidente nulls last) as rn
  from tb_cassificacao_velocidade
""")
tb_cassificacao_tipo_veiculo.createOrReplaceTempView('tb_cassificacao_tipo_veiculo')


# Criando variável numérica com contagem de acidentes por dia
tb_acidentes_dia = spark.sql("""
    select
        data_fluxo
        , count(distinct(id_acidente)) as fvl_acidentes_dia
    from tb_cassificacao_tipo_veiculo
    group by 1
""")
tb_acidentes_dia.createOrReplaceTempView('tb_acidentes_dia')


# Organizando dados para a camada stage
stage = spark.sql(f"""
  select
    id_fluxo
    , {dt_proc} as dt_proc
    , {dt_proc_book} as ref
    , tv.data_fluxo
    , fbc_classificacao_volume
    , fbc_classificacao_velocidade
    , fbc_classificacao_tipo_veiculo
    , volume_total_fluxo as flv_volume_total_fluxo
    , case when rn = 1 then fvl_acidentes_dia else null end as fvl_acidentes_dia
    , id_acidente
    , data_acidente
    , causa_acidente
    , tipo_acidente
    , classificacao_acidente
    , condicao_metereologica_acidente
    , veiculos_acidente
  from tb_cassificacao_tipo_veiculo tv
  left join tb_acidentes_dia ad on tv.data_fluxo = ad.data_fluxo
""")
stage.createOrReplaceTempView('stage')


# Conferindo quantidade de registros
qtd_registros = stage.count()


# Salvando stage na camada refined em formato parquet
stage.write.mode('append').partitionBy('ref').parquet('s3://905418122144-pod-academy-data-lake/04_refined/stage_fluxo_acidentes/')

#------------------------------ Início Carregamento Base Controle Stage ----------------------------------------#

# Criando dados de controle
df_controle_stage = spark.sql(f"""
    select
        'tb_refined_stage' as tb_name
        , {dt_proc} as dt_proc
        , {qtd_registros} as qtd_registros
""")

# Salvando dados de controle na camada refined em formato parquet
df_controle_stage.write.mode('append').parquet('s3://905418122144-pod-academy-data-lake/05_controle/refined/')

#------------------------------------------------- Book --------------------------------------------------------#

# Criando janelas de tempo do book
janelas_tempo = spark.sql(f"""
  select
    *
    , (case when months_between('{dt_proc_book_str}', data_fluxo) <= 1 then 1 else 0 end) flg_u1m
    , (case when months_between('{dt_proc_book_str}', data_fluxo) <= 3 then 1 else 0 end) flg_u3m
    , (case when months_between('{dt_proc_book_str}', data_fluxo) <= 6 then 1 else 0 end) flg_u6m
    , (case when months_between('{dt_proc_book_str}', data_fluxo) <= 9 then 1 else 0 end) flg_u9m
    , (case when months_between('{dt_proc_book_str}', data_fluxo) <= 12 then 1 else 0 end) flg_u12m
  from stage
""")
janelas_tempo.createOrReplaceTempView('janelas_tempo')


# Automatizando a geração de variáveis
fbc_1 = ['FLUXO_BAIXO', 'FLUXO_MEDIO', 'FLUXO_ALTO']
fbc_2 = ['VELOCIDADE_BAIXA', 'VELOCIDADE_MEDIA', 'VELOCIDADE_ALTA']
fbc_3 = ['VEICULO_COMERCIAL', 'VEICULO_PASSEIO', 'VEICULO_MOTO', 'VEICULO_ONIBUS']

fbcs = {
  'FBC_CLASSIFICACAO_VOLUME': fbc_1,
  'FBC_CLASSIFICACAO_VELOCIDADE':fbc_2,
  'FBC_CLASSIFICACAO_TIPO_VEICULO': fbc_3    
}

fvls = ['FLV_VOLUME_TOTAL_FLUXO','FVL_ACIDENTES_DIA']
janelas = ['1','FLG_U1M', 'FLG_U3M', 'FLG_U6M', 'FLG_U9M', 'FLG_U12M']
aggs = ['SUM', 'AVG', 'MIN', 'MAX']
count = 0

for nome_fbc,fbc in fbcs.items():
  for fbc in fbc:
    for fvl in fvls:
      for janela in janelas:
        for agg in aggs:
          print(f'{agg}(CASE WHEN {nome_fbc} = "{fbc}" AND {janela} = 1 THEN {fvl} END) as VAR_{count},')
          count += 1


# Gerando book de variáveis
book = spark.sql("""
  select
    id_fluxo,
    ref,
    SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_0,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_1,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_2,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_3,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_4,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_5,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_6,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_7,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_8,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_9,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_10,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_11,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_12,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_13,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_14,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_15,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_16,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_17,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_18,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_19,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_20,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_21,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_22,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_23,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_24,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_25,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_26,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_27,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_28,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_29,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_30,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_31,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_32,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_33,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_34,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_35,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_36,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_37,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_38,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_39,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_40,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_41,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_42,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_43,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_44,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_45,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_46,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_BAIXO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_47,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_48,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_49,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_50,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_51,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_52,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_53,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_54,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_55,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_56,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_57,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_58,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_59,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_60,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_61,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_62,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_63,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_64,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_65,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_66,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_67,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_68,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_69,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_70,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_71,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_72,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_73,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_74,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_75,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_76,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_77,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_78,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_79,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_80,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_81,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_82,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_83,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_84,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_85,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_86,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_87,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_88,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_89,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_90,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_91,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_92,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_93,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_94,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_MEDIO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_95,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_96,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_97,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_98,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_99,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_100,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_101,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_102,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_103,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_104,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_105,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_106,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_107,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_108,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_109,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_110,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_111,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_112,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_113,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_114,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_115,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_116,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_117,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_118,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_119,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_120,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_121,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_122,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_123,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_124,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_125,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_126,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_127,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_128,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_129,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_130,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_131,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_132,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_133,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_134,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_135,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_136,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_137,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_138,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_139,
SUM(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_140,
AVG(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_141,
MIN(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_142,
MAX(CASE WHEN FBC_CLASSIFICACAO_VOLUME = "FLUXO_ALTO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_143,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_144,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_145,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_146,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_147,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_148,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_149,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_150,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_151,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_152,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_153,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_154,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_155,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_156,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_157,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_158,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_159,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_160,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_161,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_162,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_163,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_164,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_165,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_166,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_167,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_168,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_169,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_170,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_171,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_172,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_173,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_174,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_175,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_176,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_177,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_178,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_179,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_180,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_181,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_182,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_183,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_184,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_185,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_186,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_187,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_188,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_189,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_190,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_BAIXA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_191,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_192,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_193,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_194,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_195,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_196,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_197,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_198,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_199,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_200,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_201,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_202,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_203,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_204,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_205,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_206,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_207,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_208,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_209,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_210,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_211,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_212,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_213,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_214,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_215,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_216,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_217,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_218,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_219,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_220,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_221,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_222,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_223,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_224,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_225,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_226,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_227,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_228,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_229,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_230,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_231,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_232,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_233,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_234,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_235,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_236,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_237,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_238,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_MEDIA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_239,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_240,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_241,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_242,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_243,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_244,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_245,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_246,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_247,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_248,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_249,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_250,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_251,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_252,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_253,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_254,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_255,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_256,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_257,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_258,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_259,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_260,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_261,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_262,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_263,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_264,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_265,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_266,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_267,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_268,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_269,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_270,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_271,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_272,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_273,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_274,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_275,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_276,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_277,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_278,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_279,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_280,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_281,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_282,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_283,
SUM(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_284,
AVG(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_285,
MIN(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_286,
MAX(CASE WHEN FBC_CLASSIFICACAO_VELOCIDADE = "VELOCIDADE_ALTA" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_287,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_288,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_289,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_290,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_291,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_292,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_293,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_294,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_295,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_296,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_297,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_298,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_299,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_300,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_301,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_302,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_303,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_304,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_305,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_306,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_307,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_308,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_309,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_310,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_311,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_312,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_313,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_314,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_315,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_316,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_317,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_318,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_319,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_320,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_321,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_322,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_323,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_324,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_325,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_326,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_327,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_328,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_329,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_330,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_331,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_332,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_333,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_334,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_COMERCIAL" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_335,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_336,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_337,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_338,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_339,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_340,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_341,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_342,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_343,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_344,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_345,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_346,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_347,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_348,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_349,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_350,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_351,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_352,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_353,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_354,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_355,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_356,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_357,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_358,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_359,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_360,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_361,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_362,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_363,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_364,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_365,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_366,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_367,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_368,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_369,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_370,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_371,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_372,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_373,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_374,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_375,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_376,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_377,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_378,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_379,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_380,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_381,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_382,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_PASSEIO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_383,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_384,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_385,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_386,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_387,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_388,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_389,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_390,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_391,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_392,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_393,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_394,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_395,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_396,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_397,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_398,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_399,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_400,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_401,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_402,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_403,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_404,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_405,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_406,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_407,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_408,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_409,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_410,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_411,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_412,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_413,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_414,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_415,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_416,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_417,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_418,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_419,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_420,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_421,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_422,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_423,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_424,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_425,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_426,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_427,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_428,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_429,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_430,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_MOTO" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_431,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_432,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_433,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_434,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND 1 = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_435,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_436,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_437,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_438,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U1M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_439,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_440,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_441,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_442,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U3M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_443,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_444,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_445,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_446,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U6M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_447,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_448,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_449,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_450,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U9M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_451,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_452,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_453,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_454,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U12M = 1 THEN FLV_VOLUME_TOTAL_FLUXO END) as VAR_455,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_456,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_457,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_458,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND 1 = 1 THEN FVL_ACIDENTES_DIA END) as VAR_459,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_460,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_461,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_462,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U1M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_463,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_464,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_465,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_466,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U3M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_467,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_468,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_469,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_470,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U6M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_471,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_472,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_473,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_474,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U9M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_475,
SUM(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_476,
AVG(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_477,
MIN(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_478,
MAX(CASE WHEN FBC_CLASSIFICACAO_TIPO_VEICULO = "VEICULO_ONIBUS" AND FLG_U12M = 1 THEN FVL_ACIDENTES_DIA END) as VAR_479
    from janelas_tempo
  group by 1,2
""")  

# Salvando book na camada refined em formato parquet
book.write.mode('append').partitionBy('ref').parquet('s3://905418122144-pod-academy-data-lake/04_refined/book_fluxo_acidentes/')

#------------------------------ Início Carregamento Base Controle Book ----------------------------------------#

# Conferindo quantidade de registros
qtd_registros_book = book.count()

# Criando dados de controle
df_controle_book = spark.sql(f"""
    select
        'tb_refined_book' as tb_name
        , {dt_proc} as dt_proc
        , {qtd_registros_book} as qtd_registros
""")

# Salvando dados de controle na camada refined em formato parquet
df_controle_book.write.mode('append').parquet('s3://905418122144-pod-academy-data-lake/05_controle/refined/')